//! 生成文件编辑拦截（H5 流式守卫的执行侧；移植 oh-my-pi
//! `coding-agent/src/tools/auto-generated-guard.ts`，快照 v18.1.2）。
//!
//! 判定两层：
//! 1. **文件名模式**（[`is_auto_generated_path`]，大小写敏感，短路、不读文件）；
//! 2. **头部注释 marker**（[`detect_content_marker`]，读文件头 1 KiB、行窗 40 行，
//!    按扩展名取注释样式后匹配 4 个严格正则）。
//!
//! 命中任意一层即视为生成文件——直接编辑生成文件从来不是用户意图（应改源头再
//! 重新生成），误拦的代价只是浪费一轮，而静默改坏的代价是上游再生成时丢失改动。

use std::path::Path;
use std::sync::LazyLock;

/// 内容检测字节窗（对齐 omp `CHECK_BYTE_COUNT`）。
const CHECK_BYTE_COUNT: usize = 1024;
/// 头部注释行窗（对齐 omp `HEADER_LINE_LIMIT`）。
const HEADER_LINE_LIMIT: usize = 40;

/// 文件名模式（对齐 omp `isAutoGeneratedFileName` 的 10 条正则；basename 不小写化）。
const FILENAME_PATTERNS_SRC: &[&str] = &[
    r"^zz_generated\.",
    r"\.pb\.(go|cc|h|c|js|ts)$",
    r"_pb2\.py$",
    r"_pb2_grpc\.py$",
    r"\.gen\.(go|ts|js|py)$",
    r"^generated\.(go|ts|js|py)$",
    r"\.swagger\.json$",
    r"\.openapi\.json$",
    r"\.mock\.(go|ts)$",
    r"\.mocks?\.(go|ts|js)$",
];

/// 已知生成器名单（对齐 omp `KNOWN_GENERATOR_PATTERN`）。
const KNOWN_GENERATORS: &str = "(?:protoc(?:-gen-[\\w-]+)?|sqlc|buf|swagger(?:-codegen)?|\
openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|\
conversion-gen|client-gen|lister-gen|informer-gen|kysely-codegen|napi-rs)";

/// 头部 marker 正则（对齐 omp `AUTO_GENERATED_HEADER_MARKERS`；保持严格——
/// `/auto-generated/` 这类宽泛模式会误伤手写文件）。
const HEADER_MARKER_SRC: &[&str] = &[
    r"@generated\b",
    r"\bcode\s+generated\s+by\s+[a-z0-9_.-]+",
    r"\bthis\s+file\s+was\s+automatically\s+generated\b",
    // 第 4 条在编译期拼入 KNOWN_GENERATORS（见 `header_marker_regexes`）。
];

/// 注释样式（对齐 omp `CommentStyle`）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CommentStyle {
    /// `//` 行注释与 `/* */` 块注释。
    Slash,
    /// `#` 行注释。
    Hash,
    /// `--` 行注释。
    Sql,
    /// `<!-- -->` 块注释。
    Html,
}

/// 扩展名 → 注释样式位表（对齐 omp `getCommentStylesForPath`）；零分配。
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
struct Styles {
    slash: bool,
    hash: bool,
    sql: bool,
    html: bool,
}

impl Styles {
    fn has(self, s: CommentStyle) -> bool {
        match s {
            CommentStyle::Slash => self.slash,
            CommentStyle::Hash => self.hash,
            CommentStyle::Sql => self.sql,
            CommentStyle::Html => self.html,
        }
    }
}

fn comment_styles_for_path(path: &str) -> Styles {
    let lower = path.to_lowercase();
    let basename = Path::new(&lower)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    if matches!(basename, "dockerfile" | "makefile" | "justfile") {
        return Styles {
            hash: true,
            ..Styles::default()
        };
    }
    let ext = Path::new(basename)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    match ext {
        "c" | "cc" | "cpp" | "cs" | "dart" | "go" | "h" | "hpp" | "java" | "js" | "jsx" | "kt"
        | "kts" | "mjs" | "cjs" | "php" | "rs" | "scala" | "swift" | "ts" | "tsx" => Styles {
            slash: true,
            ..Styles::default()
        },
        "py" | "rb" | "sh" | "bash" | "zsh" | "yml" | "yaml" | "toml" | "ini" | "cfg" | "conf"
        | "env" | "pl" | "r" => Styles {
            hash: true,
            ..Styles::default()
        },
        "sql" => Styles {
            sql: true,
            ..Styles::default()
        },
        "html" | "htm" | "xml" | "svg" | "xhtml" => Styles {
            html: true,
            ..Styles::default()
        },
        _ => Styles::default(),
    }
}

static FILENAME_RES: LazyLock<Vec<regex::Regex>> = LazyLock::new(|| {
    FILENAME_PATTERNS_SRC
        .iter()
        .map(|p| regex::Regex::new(p).expect("文件名模式正则合法"))
        .collect()
});

static HEADER_MARKERS_RES: LazyLock<Vec<regex::Regex>> = LazyLock::new(|| {
    let mut patterns: Vec<String> = HEADER_MARKER_SRC.iter().map(|s| (*s).to_string()).collect();
    patterns.push(format!(r"\bgenerated\s+by\s+{KNOWN_GENERATORS}\b"));
    patterns
        .into_iter()
        .map(|p| {
            regex::RegexBuilder::new(&p)
                .case_insensitive(true)
                .build()
                .expect("marker 正则合法")
        })
        .collect()
});

/// 第一层判定：文件名模式命中即生成文件，返回命中的 basename 作为 marker
///（对齐 omp `getAutoGeneratedMarker` 的文件名短路分支）。
#[must_use]
pub fn is_auto_generated_path(path: &str) -> Option<String> {
    let basename = path.rsplit('/').next().unwrap_or(path);
    FILENAME_RES
        .iter()
        .find(|re| re.is_match(basename))
        .map(|_| basename.to_string())
}

/// 第二层判定：从文件头内容提取头部注释，依序匹配 4 个 marker 正则，返回第一个
/// 命中的匹配文本（对齐 omp `detectAutoGeneratedMarker`；调用方负责只传头部
/// ≤[`CHECK_BYTE_COUNT`] 字节）。
#[must_use]
pub fn detect_content_marker(content: &str, path: &str) -> Option<String> {
    let header = extract_leading_header_comment(content, path);
    if header.is_empty() {
        return None;
    }
    HEADER_MARKERS_RES
        .iter()
        .find_map(|re| re.find(&header).map(|m| m.as_str().to_string()))
}

/// 提取文件头部连续注释文本（对齐 omp `extractLeadingHeaderCommentText`）：
/// 去 BOM、按行扫至 [`HEADER_LINE_LIMIT`] 行；首行 `#!` shebang 跳过；`/* */` 与
/// `<!-- -->` 块逐行收集至闭合；空行仅在已开始收集后保留；首个非注释非空行即止。
fn extract_leading_header_comment(content: &str, path: &str) -> String {
    let content = content.strip_prefix('\u{feff}').unwrap_or(content);
    if content.trim().is_empty() {
        return String::new();
    }
    let styles = comment_styles_for_path(path);
    if styles == Styles::default() {
        return String::new();
    }
    let has = |s: CommentStyle| styles.has(s);
    let mut collected: Vec<&str> = Vec::new();
    let mut started = false;
    let mut in_block: Option<BlockKind> = None;
    for (i, raw) in content.lines().take(HEADER_LINE_LIMIT).enumerate() {
        if let Some(kind) = in_block {
            collected.push(raw);
            match kind {
                BlockKind::Slash if raw.contains("*/") => in_block = None,
                BlockKind::Html if raw.contains("-->") => in_block = None,
                _ => {}
            }
            continue;
        }
        let trimmed = raw.trim_start();
        if i == 0 && trimmed.starts_with("#!") {
            continue;
        }
        if trimmed.is_empty() {
            if started {
                collected.push(raw);
            }
            continue;
        }
        let is_comment = (has(CommentStyle::Slash)
            && (trimmed.starts_with("//") || trimmed.starts_with("/*")))
            || (has(CommentStyle::Hash) && trimmed.starts_with('#'))
            || (has(CommentStyle::Sql) && trimmed.starts_with("--"))
            || (has(CommentStyle::Html) && trimmed.starts_with("<!--"));
        if !is_comment {
            break;
        }
        started = true;
        if has(CommentStyle::Slash) && trimmed.starts_with("/*") && !trimmed[2..].contains("*/") {
            in_block = Some(BlockKind::Slash);
        } else if has(CommentStyle::Html)
            && trimmed.starts_with("<!--")
            && !trimmed[4..].contains("-->")
        {
            in_block = Some(BlockKind::Html);
        }
        collected.push(raw);
    }
    collected.join("\n")
}

#[derive(Debug, Clone, Copy)]
enum BlockKind {
    Slash,
    Html,
}

/// 检查工作区相对路径是否生成文件（供工具执行侧 / 引擎流式守卫共用）：
/// 文件名短路；否则读文件头 [`CHECK_BYTE_COUNT`] 字节做 marker 检测。
/// 文件不存在 / 不可读视为非生成文件（由编辑工具自身报错）。
///
/// # Errors
/// 命中生成文件判定时返回面向模型的错误文案（含 marker）。
pub async fn assert_editable(path: &str, display_path: &str) -> Result<(), String> {
    if let Some(basename) = is_auto_generated_path(path) {
        return Err(auto_generated_error(display_path, &basename));
    }
    let Ok(bytes) = tokio::fs::File::open(path).await else {
        return Ok(());
    };
    use tokio::io::AsyncReadExt;
    let mut handle = bytes.take(CHECK_BYTE_COUNT as u64);
    let mut buf = Vec::new();
    if handle.read_to_end(&mut buf).await.is_err() {
        return Ok(());
    }
    let content = String::from_utf8_lossy(&buf);
    if let Some(marker) = detect_content_marker(&content, path) {
        return Err(auto_generated_error(display_path, &marker));
    }
    Ok(())
}

/// 错误文案（对齐 omp `buildAutoGeneratedError`，逐字语义）；流式守卫与执行侧共用。
#[must_use]
pub fn auto_generated_error(display_path: &str, detected: &str) -> String {
    format!(
        "Cannot modify auto-generated file: {display_path}\n\n\
         This file appears to be automatically generated (detected marker: \"{detected}\").\n\
         Auto-generated files should not be edited directly. Instead:\n\
         1. Find the source file or generator configuration\n\
         2. Make changes to the source\n\
         3. Regenerate the file"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filename_patterns_short_circuit() {
        assert_eq!(
            is_auto_generated_path("gen/zz_generated.types.ts").as_deref(),
            Some("zz_generated.types.ts")
        );
        assert_eq!(
            is_auto_generated_path("proto/api.pb.go").as_deref(),
            Some("api.pb.go")
        );
        assert_eq!(
            is_auto_generated_path("x/y_pb2.py").as_deref(),
            Some("y_pb2.py")
        );
        assert_eq!(
            is_auto_generated_path("a/b.gen.py").as_deref(),
            Some("b.gen.py")
        );
        assert_eq!(
            is_auto_generated_path("schema.openapi.json").as_deref(),
            Some("schema.openapi.json")
        );
        assert_eq!(
            is_auto_generated_path("mocks/user.mock.ts").as_deref(),
            Some("user.mock.ts")
        );
        assert_eq!(
            is_auto_generated_path("mocks/user.mocks.go").as_deref(),
            Some("user.mocks.go")
        );
        // 未命中
        assert_eq!(is_auto_generated_path("src/main.rs"), None);
        assert_eq!(is_auto_generated_path("src/generated_util.rs"), None);
        // 大小写敏感：Generated.TS 不是模式命中（对齐 omp 未小写化 basename）
        assert_eq!(is_auto_generated_path("Generated.ts"), None);
    }

    #[test]
    fn slash_header_marker_detected() {
        let content =
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\nfn main() {}\n";
        let marker = detect_content_marker(content, "api.pb.cc");
        assert!(marker.is_some());
        assert!(marker.unwrap().contains("protoc-gen-go"));
    }

    #[test]
    fn hash_header_marker_detected() {
        let content = "# This file was automatically generated by foo.\nimport os\n";
        assert!(detect_content_marker(content, "gen/x.py").is_some());
    }

    #[test]
    fn sql_and_html_styles() {
        assert!(
            detect_content_marker("-- @generated by sqlc\nSELECT 1;\n", "db/query.sql").is_some()
        );
        assert!(
            detect_content_marker("<!-- @generated -->\n<html></html>\n", "ui/icon.svg").is_some()
        );
    }

    #[test]
    fn non_header_mention_ignored() {
        // marker 出现在头部注释之外 → 不命中（omp 严格性）
        let content = "package main\n// @generated\nfn main() {}\n";
        assert_eq!(detect_content_marker(content, "main.go"), None);
    }

    #[test]
    fn unknown_extension_no_content_check() {
        // 未知扩展名无注释样式 → 不做内容检测（但文件名模式仍可命中）
        let content = "@generated\n";
        assert_eq!(detect_content_marker(content, "data.bin"), None);
    }

    #[test]
    fn shebang_line_skipped() {
        let content = "#!/usr/bin/env bash\n# @generated by buf\nset -e\n";
        assert!(detect_content_marker(content, "run.sh").is_some());
    }

    #[test]
    fn slash_block_comment_collected() {
        let content = "/*\n * @generated\n */\npackage main\n";
        assert!(detect_content_marker(content, "main.go").is_some());
    }

    #[test]
    fn bom_stripped_before_detection() {
        let content = "\u{feff}// Code generated by stringer. DO NOT EDIT.\npackage x\n";
        assert!(detect_content_marker(content, "en.go").is_some());
    }

    #[test]
    fn beyond_40_lines_ignored() {
        let mut content = String::from("package x\n");
        content.push_str(&"// fill\n".repeat(45));
        content.push_str("// @generated\n");
        assert_eq!(detect_content_marker(&content, "late.go"), None);
    }
}
